apiVersion: v1
kind: Pod
metadata:
  name: nodejs-basic
  namespace: docker-basics
  labels:
    app: nodejs-basic
    env: staging
spec:
  containers:
    - name: nodejs-basics
      image: thydreamtech/docker-session:basic
      imagePullPolicy: Always
      env:
        - name: APP_PORT
          value: "8091"
      ports:
        - containerPort: 8091
          name: http
          protocol: TCP
  imagePullSecrets:
    - name: regcred
